// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetFlex.DAL.EF;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetFlex.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220513225626_initialMigrate")]
    partial class initialMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NetFlex.DAL.EF.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewVideo")
                        .HasColumnType("text");

                    b.Property<Guid>("SerialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("VideoLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("956a7fa2-75c8-41ef-97a8-79771b1478bc"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("37619272-5108-459c-b083-63033645acae"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("553cf3e5-80cc-4f0b-b548-1c10adc8063a"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("2f33d4de-9677-4a39-ae1b-c721c8359d20"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("a69f5ebb-389f-4f5f-90e0-2f27f944a847"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("013e23c9-90bb-4ac2-b860-e3e5bdfe34e7"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("ad0d23ba-e27c-454d-bf76-d4162a6b7787"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("b693afc9-9269-414c-80a2-622bad630d29"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("96f3abfd-3426-4330-a09f-3f34a6a10970"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("5cd884d6-98ca-4bcc-97ff-2a8f5c177fc7"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("b711d1dc-c731-4c0d-ab34-c634366f9822"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("413d1adb-1398-4dac-ad19-7fe314388e6f"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("0a371828-6959-46a5-addd-6ba375363bbb"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("1801fd09-6bfe-48aa-a5b8-48cd412b8a42"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("5a9289ee-e67e-439c-9900-78dc9ce01602"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("ffc51f51-931b-401f-a542-c0851bdbecc9"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("63c51cae-b49c-4403-aa9a-495004306360"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("94ec60aa-b071-4f24-93d7-544339a7806f"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("158f67a7-6d9b-4211-99e3-e4a0c1ccd52a"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("7d8bbc2d-7004-4d85-99c9-0466dfa07c61"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("903abe10-1a8f-4aef-9137-4f975145d290"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("3c8b2096-de30-4458-a8e3-c29c90bd0da9"),
                            Duration = 24,
                            Number = 1,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("c380a445-d389-4235-8940-fa06beb5fba5"),
                            Duration = 24,
                            Number = 2,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("a1445f1b-ee36-41fc-a24d-46895895cc4e"),
                            Duration = 24,
                            Number = 3,
                            PreviewVideo = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/Netflix%20icon.svg",
                            SerialId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            Title = "Красный эпизод",
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        });
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.Film", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Poster")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<float>("UserRating")
                        .HasColumnType("real");

                    b.Property<string>("VideoLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c7e4f35-7ca4-4f04-9d5a-5f68b176556d"),
                            AgeRating = 16,
                            Description = "Aмериканский художественный фильм-драма 1994 года, снятый режиссёром Фрэнком Дарабонтом по его же сценарию, и рассказывающий историю Энди Дюфрейна, незаслуженно приговорённого к пожизненному заключению и пробывшего в заключении почти 20 лет. Основой сюжета послужила повесть Стивена Кинга «Рита Хейуорт и спасение из Шоушенка». Главные роли сыграли Тим Роббинс и Морган Фримен",
                            Duration = 142,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/thumb/d/de/Movie_poster_the_shawshank_redemption.jpg/317px-Movie_poster_the_shawshank_redemption.jpg",
                            Title = "Побег из Шоушенка",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("62fc461a-83e9-496e-a6b5-fab6cc1b8adf"),
                            AgeRating = 16,
                            Description = "Действие фильма происходит в футуристическом Лос-Анджелесе, где рядом с обычными людьми сосуществуют искусственные создания — «репликанты». Главный герой, полицейский-репликант Кей, случайно вскрывает старый секрет, способный нарушить существующий порядок, и вынужден разыскивать Рика Декарда, героя первого фильма. ",
                            Duration = 163,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/thumb/9/9b/%D0%91%D0%B5%D0%B3%D1%83%D1%89%D0%B8%D0%B9_%D0%BF%D0%BE_%D0%BB%D0%B5%D0%B7%D0%B2%D0%B8%D1%8E_2049.jpg/300px-%D0%91%D0%B5%D0%B3%D1%83%D1%89%D0%B8%D0%B9_%D0%BF%D0%BE_%D0%BB%D0%B5%D0%B7%D0%B2%D0%B8%D1%8E_2049.jpg",
                            Title = "Бегущий по лезвию 2049",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("e2cb3d51-4e41-46b7-98da-1fe17e83ee40"),
                            AgeRating = 16,
                            Description = "Доминик Кобб и Артур — «извлекатели»: они занимаются корпоративным шпионажем, используя экспериментальные военные технологии, чтобы проникнуть в подсознание своих «целей» и извлечь информацию через общий мир снов. Их последняя цель, Сайто, рассказывает, что устроил встречу, чтобы проверить: сможет ли Кобб выполнить кажущуюся невозможной работу — внедрение идеи в подсознание человека, или «начало». Сайто хочет, чтобы Кобб убедил Роберта Фишера, сына больного конкурента Сайто, Мориса Фишера, развалить компанию его отца. Взамен Сайто обещает «всего одним звонком» помочь Коббу, над которым «висит» ложное обвинение в убийстве жены, легально вернуться в США, где остались его дети. ",
                            Duration = 148,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/thumb/b/bc/Poster_Inception_film_2010.jpg/318px-Poster_Inception_film_2010.jpg",
                            Title = "Начало",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("d07b4bf0-dc65-4370-9b75-7beae106e40c"),
                            AgeRating = 12,
                            Description = "Марти Макфлай — обычный семнадцатилетний американский подросток, живущий в 1985 году в неблагополучной семье Макфлаев в городке Хилл-Вэлли (штат Калифорния). Его отец Джордж постоянно терпит издевательства и насмешки своего шефа Биффа Таннена, а мать Лоррейн — алкоголичка с избыточным весом. Утром 25 октября 1985 года Марти по дороге в школу заходит домой к своему другу-учёному, доктору Эмметту Брауну по прозвищу Док, но самого его не застаёт. Док звонит Марти и просит встретиться в 1:15 ночи на автостоянке у торгового центра «Две сосны», дабы показать ему нечто удивительное.",
                            Duration = 116,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/thumb/9/90/BTTF_DVD_rus.jpg/300px-BTTF_DVD_rus.jpg",
                            Title = "Назад в будущее",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("3a82b37b-7a41-4c94-ab89-f2a6d1647981"),
                            AgeRating = 16,
                            Description = "Отец Акио, мать Юко и их десятилетняя дочь Тихиро переезжают в новый дом, расположенный где-то в глубинке Японии. Перепутав дорогу к новому дому и проехав через странный лес, они попадают в тупик: останавливаются перед высокой стеной, в которой темнеет вход. Войдя туда и проследовав по длинному тёмному туннелю, они попадают в здание, похожее на вокзал, выйдя из которого, оказываются в пустующем городке, почти полностью состоящем из пустующих ресторанов. Нигде нет ни души.",
                            Duration = 163,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/6/61/Spirited_away.jpg",
                            Title = "Унесённые призраками",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("84951f4c-e4f6-4b3f-af74-ca0acdd17e47"),
                            AgeRating = 12,
                            Description = "Труман Бёрбанк — обычный человек, работающий страховым агентом и живущий обычной жизнью. Однако он не знает, что за каждым его движением наблюдают многочисленные скрытые камеры, а его жизнь круглосуточно передаётся в прямом эфире по всему миру. Родина Трумана — город Сихэвэн (Seahaven, дословно – «Морская гавань») на острове вблизи материка — на самом деле искусно выполненные декорации, а всё население — нанятые актёры. Исполнительный продюсер «Шоу Трумана», Кристоф, с помощью своей команды может даже изменять погоду в городе с помощью технологий под огромным куполом киностудии. ",
                            Duration = 103,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/c/cd/Trumanshow.jpg",
                            Title = "Шоу Трумана",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("5de968e8-e920-4814-91d3-e67450f0f66b"),
                            AgeRating = 16,
                            Description = "Парализованный богатый аристократ Филипп, ставший инвалидом после того, как разбился на параплане, ищет себе помощника, который должен за ним ухаживать. Одного из кандидатов, чернокожего Дрисса, работа не интересует — ему нужен формальный письменный отказ, чтобы продолжать получать пособие по безработице.",
                            Duration = 112,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/b/b9/Intouchables.jpg",
                            Title = "1+1",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("4e58585b-4581-4737-908c-7fcc5765c5d5"),
                            AgeRating = 18,
                            Description = "Во время комендантского часа поздним вечером 4 ноября неизвестного года человек, носящий маску Гая Фокса и называющий себя «V» («Ви»), спасает из рук Службы Безопасности Norsefire (в фильме её сотрудники именуются Пальцами) ассистентку британского телеканала British Television Network (BTN) Иви Хэммонд. V сообщает Иви, что он «музыкант» и приглашает её послушать его «выступление» на крышу здания около центрального уголовного суда Лондона — Олд-Бейли.",
                            Duration = 132,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/a/ae/V_For_Vendetta_2006_Poster_01.jpg",
                            Title = "V — значит вендетта",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("8dc46d99-c504-4654-919b-baa2e1c92df4"),
                            AgeRating = 12,
                            Description = "Фродо с Сэмом продолжают путь в Мордор. Фродо видит в ночных кошмарах Гэндальфа, упавшего вместе с Балрогом на дно бездны. Хоббиты заблудились в скалистой местности. Ночью они захватывают в плен преследовавшего их Голлума. Он соглашается отвести героев в Мордор. Саруман после общения с Сауроном посредством палантира посылает отряды урук-хай и горцев Дунланда на земли Рохана.",
                            Duration = 235,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/f/f0/The_Lord_of_the_Rings._The_Two_Towers_%E2%80%94_movie.jpg",
                            Title = "Властелин колец: Две крепости",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        },
                        new
                        {
                            Id = new Guid("cf259f11-44f1-405f-99af-8f759f83c387"),
                            AgeRating = 16,
                            Description = "Гражданская война продолжается. Несмотря на уничтожение «Звезды смерти», Галактическая Империя захватила базу повстанцев на планете Явин IV и продолжает поиски мятежников. Альянс повстанцев устраивает новую базу на далёкой замёрзшей планете Хот, на самом краю Галактики. Дарт Вейдер лично руководит поиском повстанцев. По его приказу во все уголки Галактики рассылаются зонды-разведчики. ",
                            Duration = 124,
                            Poster = "https://upload.wikimedia.org/wikipedia/ru/thumb/e/e0/Empire20strikes20back_old.jpg/345px-Empire20strikes20back_old.jpg",
                            Title = "Звёздные войны. Эпизод V: Империя наносит ответный удар",
                            UserRating = 0f,
                            VideoLink = "https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/Blend%20S%20OP%20Opening%E3%80%8CUHD%2060FPS%E3%80%8D.mp4"
                        });
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GenreName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4e281d3-6e31-4fb0-bd55-857bd85cea39"),
                            GenreName = "Комедия"
                        },
                        new
                        {
                            Id = new Guid("8b709613-41ac-444b-a8dd-ad08e2c7ac08"),
                            GenreName = "Мультфильм"
                        },
                        new
                        {
                            Id = new Guid("f40501bc-7bfd-4deb-9c3c-f8bc7ce6a341"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("3ff8af45-a075-45dd-a1e8-de9147c04310"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("49d63065-6584-44fb-b464-508914e01321"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("e1150fa6-22a4-444e-b083-2bce3daf88e4"),
                            GenreName = "Боевик"
                        },
                        new
                        {
                            Id = new Guid("7a1fb135-382f-48d2-a510-a1629f28eb7a"),
                            GenreName = "Мелодрама"
                        },
                        new
                        {
                            Id = new Guid("5d4dd301-06c5-4946-ae14-1b835e54ec3c"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("89e89743-533e-4ba6-b1d0-a482744f2f52"),
                            GenreName = "Приключение"
                        },
                        new
                        {
                            Id = new Guid("ae19bdc1-0be5-414b-adfd-8918917c8539"),
                            GenreName = "Аниме"
                        });
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.GenreVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenreName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GenreVideos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("438c84f0-995e-4f9b-b3b7-726078792b09"),
                            ContentId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("fc1c2a86-3eb6-4698-acd5-ebe99a74aefd"),
                            ContentId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("c1cf8948-4901-4c1d-b0df-661b546c544e"),
                            ContentId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("06aba487-412a-4494-b33d-1ba7689e634a"),
                            ContentId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("f2a8f0ac-5454-4dad-a8eb-1b205c264769"),
                            ContentId = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("8a286a51-6754-4c44-b211-62c75d9c217b"),
                            ContentId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("06cd8527-33a1-4770-8182-b00b3f98e961"),
                            ContentId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("8a9fef42-509f-4450-99d4-6dd469b623ce"),
                            ContentId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("aa55c76c-d9a7-42c0-a902-44485d46eaf1"),
                            ContentId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("df69a0b9-2be4-4a8f-ae05-2f9c03705e5a"),
                            ContentId = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("7cd4200b-a4e0-40d6-b9fa-65439a6cfcb5"),
                            ContentId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("d367a978-f0e1-42e0-8c78-460ff833f439"),
                            ContentId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("7add3790-cc5d-4deb-ab68-6732b0f582c1"),
                            ContentId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("10e40fca-c269-4434-9e26-d426c989506e"),
                            ContentId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("461b9176-d10e-490a-9138-9700acd64039"),
                            ContentId = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("68b1217f-d627-4481-bfbf-c709767e3eae"),
                            ContentId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("f86c8451-febf-49dc-be1f-6303df264f98"),
                            ContentId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("f6315bf4-9aac-42e2-82a2-cc99753e7649"),
                            ContentId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("0232d776-8b71-42ae-b391-bf217512fb79"),
                            ContentId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("0e712110-4d8d-4bac-a0dc-759049498666"),
                            ContentId = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("ea74bb1b-b22d-4c2a-864e-e3e299f14ec9"),
                            ContentId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("c77cd68f-5aa5-418b-bc9b-10f23fcc20dd"),
                            ContentId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("06177805-6391-4a60-a0bf-48c3198c9a97"),
                            ContentId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("c300b5e3-4987-43cb-ae46-82a5f7f6e369"),
                            ContentId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("cbf55b83-fdad-4b4b-a669-7df61247a9cf"),
                            ContentId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("67baf5d3-c06a-4215-b28c-5aaae9824a41"),
                            ContentId = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("b8e483f5-9e54-478b-b124-86c6af0e3c94"),
                            ContentId = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("d78c421b-d935-454a-a9a7-960e786a44f7"),
                            ContentId = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("481cf384-6811-4d2a-84fd-f333753d5753"),
                            ContentId = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("e02263df-06d2-4013-b711-dc2ff0439db9"),
                            ContentId = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("26e65086-72ec-4147-85b2-64c533b25728"),
                            ContentId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("523e3301-3ddc-48f7-8357-dc3683eaf86c"),
                            ContentId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("15aba693-5e0e-4291-938b-9afb6ecc7d26"),
                            ContentId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("b56d4bb7-379d-458a-9f00-e15582d2bdf1"),
                            ContentId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("45b588ba-2572-4e5e-9cf4-0dbdfad6f77d"),
                            ContentId = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("7e15f7f1-ed98-4bf3-ba4c-b4ff2d8dcbb8"),
                            ContentId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("d8e3dd1d-e10b-46c5-9f34-4a4c2482097d"),
                            ContentId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("1e2f8ca1-d067-434f-a63c-e48d6f37a873"),
                            ContentId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("b019d121-49bb-4c35-9658-dfc6f281b022"),
                            ContentId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("4cbf4e13-b35b-44ae-8a1a-40e9051843e4"),
                            ContentId = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("ac6f12f8-35f6-43dc-a9bf-1babc0191cf8"),
                            ContentId = new Guid("5c7e4f35-7ca4-4f04-9d5a-5f68b176556d"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("bd592100-7a37-493f-9e72-b3fddb009a08"),
                            ContentId = new Guid("5c7e4f35-7ca4-4f04-9d5a-5f68b176556d"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("09df3bff-a2e1-4c5e-90bd-a7a65f92aa88"),
                            ContentId = new Guid("5c7e4f35-7ca4-4f04-9d5a-5f68b176556d"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("ab4bcacd-f666-4dd8-a101-a71f86af3edc"),
                            ContentId = new Guid("5c7e4f35-7ca4-4f04-9d5a-5f68b176556d"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("09a330df-9bed-4b86-be67-13d45e7d4468"),
                            ContentId = new Guid("5c7e4f35-7ca4-4f04-9d5a-5f68b176556d"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("bb6445c5-0b30-49be-9560-cfa46fe02752"),
                            ContentId = new Guid("62fc461a-83e9-496e-a6b5-fab6cc1b8adf"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("22c5169e-37ce-4302-9d53-3325b61827e7"),
                            ContentId = new Guid("62fc461a-83e9-496e-a6b5-fab6cc1b8adf"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("1034a4f2-05cd-48d8-9646-ce9e2017d0a8"),
                            ContentId = new Guid("62fc461a-83e9-496e-a6b5-fab6cc1b8adf"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("7e5a9472-84cb-4c1b-8a30-77b8595ec4e5"),
                            ContentId = new Guid("62fc461a-83e9-496e-a6b5-fab6cc1b8adf"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("2bb6eaca-0c7d-4fb6-9f24-4f71a46e54cc"),
                            ContentId = new Guid("62fc461a-83e9-496e-a6b5-fab6cc1b8adf"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("90d3ecff-2095-4916-8a01-43e736c08b2e"),
                            ContentId = new Guid("e2cb3d51-4e41-46b7-98da-1fe17e83ee40"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("aa22573e-6b46-48fe-a66b-38bde7d2b162"),
                            ContentId = new Guid("e2cb3d51-4e41-46b7-98da-1fe17e83ee40"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("39488a3a-130b-4dd0-83b3-f7961ebb528a"),
                            ContentId = new Guid("e2cb3d51-4e41-46b7-98da-1fe17e83ee40"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("2118a74a-6a87-4111-b26a-1fc20fe28d1d"),
                            ContentId = new Guid("e2cb3d51-4e41-46b7-98da-1fe17e83ee40"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("a9567e11-6250-4990-8922-3bed4e7a95a1"),
                            ContentId = new Guid("e2cb3d51-4e41-46b7-98da-1fe17e83ee40"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("6ef25aa5-329d-424e-a2ce-c205a184ae9d"),
                            ContentId = new Guid("d07b4bf0-dc65-4370-9b75-7beae106e40c"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("25289b9c-8782-4355-9378-8e4488825d94"),
                            ContentId = new Guid("d07b4bf0-dc65-4370-9b75-7beae106e40c"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("3ac0c6f8-9470-4ff2-a84e-dbe0e6367c0e"),
                            ContentId = new Guid("d07b4bf0-dc65-4370-9b75-7beae106e40c"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("fc3ded5b-cd77-4acd-91a9-d9426d0a2504"),
                            ContentId = new Guid("d07b4bf0-dc65-4370-9b75-7beae106e40c"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("33632db3-30b1-46a1-86ae-1124935d45d7"),
                            ContentId = new Guid("d07b4bf0-dc65-4370-9b75-7beae106e40c"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("b0dc3b2f-e3e4-48b7-b01a-c835f32c556d"),
                            ContentId = new Guid("3a82b37b-7a41-4c94-ab89-f2a6d1647981"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("c873ba28-0785-4df0-b2a0-5422ef064173"),
                            ContentId = new Guid("3a82b37b-7a41-4c94-ab89-f2a6d1647981"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("1d43e88d-43e8-4d4c-ae72-7bff11cefb93"),
                            ContentId = new Guid("3a82b37b-7a41-4c94-ab89-f2a6d1647981"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("a05fdaf4-4aab-4e0b-be6c-3430ce6d1c30"),
                            ContentId = new Guid("3a82b37b-7a41-4c94-ab89-f2a6d1647981"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("39c74f4f-0782-4ec2-8f68-fab7ce76eecb"),
                            ContentId = new Guid("3a82b37b-7a41-4c94-ab89-f2a6d1647981"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("c0c0cf21-da71-4342-9b4a-3f588240ad2d"),
                            ContentId = new Guid("84951f4c-e4f6-4b3f-af74-ca0acdd17e47"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("8a825fde-fcc0-4927-8a64-d677957b1216"),
                            ContentId = new Guid("84951f4c-e4f6-4b3f-af74-ca0acdd17e47"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("6ed2d786-4967-4ddf-b296-ac140e2324be"),
                            ContentId = new Guid("84951f4c-e4f6-4b3f-af74-ca0acdd17e47"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("a608f33e-02ab-4acf-86fb-4d8bd727a34b"),
                            ContentId = new Guid("84951f4c-e4f6-4b3f-af74-ca0acdd17e47"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("119d2f74-a0a2-45e9-8e45-548e99f4547c"),
                            ContentId = new Guid("84951f4c-e4f6-4b3f-af74-ca0acdd17e47"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("4ab6745f-464b-4dd5-81dc-47b1cdc065ae"),
                            ContentId = new Guid("5de968e8-e920-4814-91d3-e67450f0f66b"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("ae65ab34-6f02-4c60-9d72-fca7ecc73d93"),
                            ContentId = new Guid("5de968e8-e920-4814-91d3-e67450f0f66b"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("8d8b0177-e8a0-4296-af4b-a80a8815740a"),
                            ContentId = new Guid("5de968e8-e920-4814-91d3-e67450f0f66b"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("ccd99489-c418-4470-a5b0-1ba7bfc4c868"),
                            ContentId = new Guid("5de968e8-e920-4814-91d3-e67450f0f66b"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("3d044f84-365f-40fe-89cb-ae5384712191"),
                            ContentId = new Guid("5de968e8-e920-4814-91d3-e67450f0f66b"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("bfc6960c-ace4-45e3-a541-ca526bc3fc19"),
                            ContentId = new Guid("4e58585b-4581-4737-908c-7fcc5765c5d5"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("0b7a9f6a-1fee-4b12-80af-c8e0ea1ece82"),
                            ContentId = new Guid("4e58585b-4581-4737-908c-7fcc5765c5d5"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("8347a4be-4f82-4d66-9959-e400c4134748"),
                            ContentId = new Guid("4e58585b-4581-4737-908c-7fcc5765c5d5"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("198ba5d8-5590-4be1-96d7-6c44d1e67c3e"),
                            ContentId = new Guid("4e58585b-4581-4737-908c-7fcc5765c5d5"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("e3a579c7-9b2e-41f5-9a83-d0b8fc7fb93f"),
                            ContentId = new Guid("4e58585b-4581-4737-908c-7fcc5765c5d5"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("ee8d8cf3-d331-437a-a60c-792418c6c66e"),
                            ContentId = new Guid("8dc46d99-c504-4654-919b-baa2e1c92df4"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("c413c51c-5457-4771-bdc4-f045ba0d7403"),
                            ContentId = new Guid("8dc46d99-c504-4654-919b-baa2e1c92df4"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("2fc4b1d4-e91e-4dc1-9c0c-ee172b9b9b4b"),
                            ContentId = new Guid("8dc46d99-c504-4654-919b-baa2e1c92df4"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("00bcbb4d-a3c6-4ffa-be6f-04ffd52fcf35"),
                            ContentId = new Guid("8dc46d99-c504-4654-919b-baa2e1c92df4"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("86d59150-cff1-4cb7-b54b-7ccafc989aa4"),
                            ContentId = new Guid("8dc46d99-c504-4654-919b-baa2e1c92df4"),
                            GenreName = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("c5bfb88c-1ce4-4de6-9f68-30ba4410d71e"),
                            ContentId = new Guid("cf259f11-44f1-405f-99af-8f759f83c387"),
                            GenreName = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("8f13d5a9-4b0d-47d2-9d52-250d69ac6fe2"),
                            ContentId = new Guid("cf259f11-44f1-405f-99af-8f759f83c387"),
                            GenreName = "Ужасы"
                        },
                        new
                        {
                            Id = new Guid("7d44a080-ada3-4ae8-a186-138c4fca1245"),
                            ContentId = new Guid("cf259f11-44f1-405f-99af-8f759f83c387"),
                            GenreName = "Триллер"
                        },
                        new
                        {
                            Id = new Guid("eae1d646-1517-48bb-b8bd-dee390ba6f29"),
                            ContentId = new Guid("cf259f11-44f1-405f-99af-8f759f83c387"),
                            GenreName = "Драма"
                        },
                        new
                        {
                            Id = new Guid("44736b79-6057-40f1-9c01-169f5d5d923e"),
                            ContentId = new Guid("cf259f11-44f1-405f-99af-8f759f83c387"),
                            GenreName = "Детектив"
                        });
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<float>("UserRating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.Serial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("NumEpisodes")
                        .HasColumnType("integer");

                    b.Property<string>("Poster")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<float>("UserRating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Serials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74d03f01-8ae1-4c6f-be51-8c5d0a435958"),
                            AgeRating = 16,
                            Description = "Братья Винчестеры стараются не выпустить демонов. Фантастический сериал, вдохновленный «Сумеречной зоной»",
                            NumEpisodes = 24,
                            Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/c2c45ca9-0270-4bb2-bb82-5de3f01effbc/300x450",
                            Title = "Сверхъестественное",
                            UserRating = 0f
                        },
                        new
                        {
                            Id = new Guid("7e1e4355-2766-4341-a7a5-ad1d97d2f143"),
                            AgeRating = 12,
                            Description = "Близнецы проводят каникулы у странного прадядюшки. Тайны и аномалии в захватывающем мультсериале Алекса Хирша",
                            NumEpisodes = 48,
                            Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/04954219-061a-4646-a7d6-054fdc34b053/300x450",
                            Title = "Гравити Фолз",
                            UserRating = 0f
                        },
                        new
                        {
                            Id = new Guid("2235d369-639d-4858-9c0c-abd8588c3f0a"),
                            AgeRating = 18,
                            Description = "Умирающий учитель химии начинает варить мет ради благополучия семьи. Выдающийся драматический сериал 2010-х",
                            NumEpisodes = 34,
                            Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/fb35416f-3b0d-4b96-bc65-cf6923f9e329/300x450",
                            Title = "Во все тяжкие",
                            UserRating = 0f
                        },
                        new
                        {
                            Id = new Guid("83f8384a-fc2c-4d98-b3a8-5a867f931361"),
                            AgeRating = 16,
                            Description = "1980-е годы, тихий провинциальный американский городок. Благоприятное течение местной жизни нарушает загадочное исчезновение подростка по имени Уилл.",
                            NumEpisodes = 12,
                            Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/4639b97f-1ff6-4f63-b7f6-02ea1a14f553/300x450",
                            Title = "Очень странные дела",
                            UserRating = 0f
                        },
                        new
                        {
                            Id = new Guid("08c98868-37c3-47c2-95cd-e94b39871ec4"),
                            AgeRating = 12,
                            Description = "Адаптация книг Артура Конан Дойля о детективе Шерлоке Холмсе и его напарнике Джоне Ватсоне, в которой действие перенесено в XXI век",
                            NumEpisodes = 64,
                            Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/f28c1ea2-47b0-49d5-b11c-9608744f0233/300x450",
                            Title = "Шерлок",
                            UserRating = 0f
                        },
                        new
                        {
                            Id = new Guid("af3f94c6-348d-439d-a649-06e8f35db631"),
                            AgeRating = 16,
                            Description = "История данного сериала пойдет про гулей и борьбу с ними. Гуль – это некое животное, которое питается людьми, и сейчас все Токио просто кишит ними.",
                            NumEpisodes = 12,
                            Poster = "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a662e7da753f.jpg",
                            Title = "Токийский гуль",
                            UserRating = 0f
                        },
                        new
                        {
                            Id = new Guid("0c4003ae-7668-4785-9da0-e0c983e35975"),
                            AgeRating = 18,
                            Description = "Семь Королевств борются за Железный трон. Самый масштабный и обсуждаемый сериал 2010-х годов",
                            NumEpisodes = 1000,
                            Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/dd78edfd-6a1f-486c-9a86-6acbca940418/300x450",
                            Title = "Игра престолов",
                            UserRating = 0f
                        },
                        new
                        {
                            Id = new Guid("f997d15f-db67-4d76-8004-83d129f2b234"),
                            AgeRating = 16,
                            Description = "Друзья пытаются оживить окаменевшее человечество, но у них есть противник. Сай-фай-аниме о борьбе идеологий",
                            NumEpisodes = 24,
                            Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/54aae4e5-62b8-4572-8f97-3761743be082/300x450",
                            Title = "Доктор Стоун",
                            UserRating = 0f
                        });
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("NetFlex.DAL.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NetFlex.DAL.EF.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NetFlex.DAL.EF.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetFlex.DAL.EF.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NetFlex.DAL.EF.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
